#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a irc desktop='^3'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a flashplayer state=tiled
bspc rule -a Flashplayer state=tiled
bspc config border_radius 15

bspc rule -a scratchterm sticky=on state=floating hidden=on

$HOME/.config/polybar/launch.sh &

firefox &
discord &
pidof bspswallow || bspswallow &
$TERMINAL -c irc -e mosh nikky &
